version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build_and_test: 
    steps:
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
